name: Create Pre-Release
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Pre-release tag (e.g., v1.0.0-rc.1)'
        required: true
        type: string
      release_title:
        description: 'Title for the pre-release'
        required: true
        type: string

jobs:
  build:
    name: Create Pre-Release
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 20.x ]

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      FILE_NAME: zendesk-gridx-health-check_${{ inputs.tag_name }}
      ZENDESK_SUBDOMAIN: ${{  secrets.ZENDESK_SUBDOMAIN  }}
      ZENDESK_EMAIL: ${{  secrets.ZENDESK_EMAIL  }}
      ZENDESK_API_TOKEN: ${{  secrets.ZENDESK_API_TOKEN  }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install zcli
        run: npm i @zendesk/zcli -g

      - name: Install app dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Package Zendesk App
        run: |
          zcli apps:package dist
          mv ./dist/tmp/*.zip ./dist/tmp/${{ env.FILE_NAME }}.zip

      - name: Create Pre-Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ inputs.tag_name }}
          release_name: ${{ inputs.release_title }}
          draft: false
          prerelease: true

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/tmp/*.zip
          asset_name: ${{ env.FILE_NAME }}.zip
          asset_content_type: application/zip